In [4]:
import numpy as np
import cv2

capture = cv2.VideoCapture(0)

faceModel = "C:/Users/Inspiron/open cv/hascadeClassifier.xml"
face_detector = cv2.CascadeClassifier(faceModel)

while(True):
    # Capture frame-by-frame
    ret, frame = capture.read()
    frame = cv2.flip(frame,1)
    faces = face_detector.detectMultiScale(frame,1.1,0)
    if len(faces) != 0:
        x,y,w,h = faces[0]
        frame = cv2.rectangle(frame,(x,y),(x+w,y+h),(0,0,255),2)
    print(faces)
    # Our operations on the frame come here
    
    
    # Display the resulting frame
    cv2.imshow('video',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
capture.release()
cv2.destroyAllWindows()

[[178 215 148 148]
 [185 215 148 148]
 [158 177 197 197]]
[[170 188 179 179]
 [158 177 197 197]]
[[178 215 148 148]
 [188 229 135 135]]
[[188 229 135 135]
 [178 215 148 148]]
[[188 229 135 135]
 [ 50 150  84  84]
 [190 232 122 122]
 [171 195 163 163]
 [178 215 148 148]]
[[190 232 122 122]]
[[161 188 179 179]
 [148  57  76  76]
 [ 50 150  84  84]]
[[151 239  63  63]
 [144 232  76  76]
 [178 239 111 111]]
()
[[ 50 150  84  84]]
[[405 242  84  84]]
[[ 50 150  84  84]]
()
()
()
()
[[161 188 179 179]
 [171 195 163 163]]
[[161 188 179 179]
 [158 177 197 197]]
()
[[179 188 179 179]
 [111  65  24  24]
 [134 204  20  20]]
[[298 232  63  63]
 [179 188 179 179]]
[[185 215 148 148]]
()
()
[[ 99 159  76  76]]
()
()
[[ 99 159  76  76]
 [152 216  92  92]]
()
()
[[ 99 156  76  76]]
()
[[167 167 197 197]
 [169 210  63  63]
 [170 170 179 179]]
[[179 179 163 163]
 [167 167 197 197]
 [182 225  43  43]]
[[170 179 179 179]
 [179 179 179 179]
 [167 167 197 197]]
()
()
()
()
[[356 208  43  43]]
()
[[384 438  

[[167 197 197 197]
 [123 202  22  22]]
()
[[187 220 163 163]]
[[ 84 150  84  84]]
[[ 84 150  84  84]
 [179 236 163 163]]
[[ 84 150  84  84]]
()
()
()
()
[[121 202  22  22]]
[[121 202  22  22]]
[[122 202  20  20]
 [121 202  22  22]]
[[ 42 146  84  84]
 [121 202  22  22]]
()
[[ 42 146  84  84]
 [122 202  20  20]]
[[140 327  24  24]
 [ 42 146  84  84]]
()
()
()
[[150 332  20  20]]
()
()
()
()
()
()
()
()
()
[[325 133  27  27]]
()
[[171 324  52  52]]
()
()
()
()
()
[[ 37 142  92  92]]
()
[[122 202  20  20]]
()
()
()
[[ 30 142 101 101]
 [122 202  20  20]]
()
()
[[114  61  29  29]]
()
()
[[129  53  63  63]]
()
()
()
()
()
()
()
()
()
()
()
[[106  61  27  27]]
()
()
()
()
[[108  61  29  29]]
()
()
()
()
()
()
[[163 236 163 163]
 [171 236 163 163]]
()
()
[[163 220 163 163]
 [163 228 163 163]]
[[163 212 163 163]]
[[152 197 179 179]
 [171 195 163 163]
 [178 215 148 148]]
[[152 188 179 179]
 [161 188 179 179]
 [163 195 163 163]]
[[143 188 179 179]
 [161 188 179 179]
 [171 195 163 163]
 [122 204  

[[236 238  43  43]
 [201 221  84  84]
 [205 221  84  84]
 [209 221  84  84]
 [202 196 122 122]
 [209 220  76  76]
 [213 224  76  76]]
[[233 233  47  47]
 [233 231  52  52]
 [213 224  76  76]
 [198 216  92  92]]
[[207 224  69  69]
 [201 221  84  84]
 [205 220  76  76]
 [206 200 111 111]]
[[207 224  69  69]
 [211 224  69  69]
 [202 196 122 122]
 [207 228  69  69]
 [ 95 156  76  76]
 [205 220  76  76]
 [209 220  76  76]]
[[207 224  69  69]
 [185 192 148 148]
 [205 220  76  76]]
[[236 233  47  47]]
[[202 202 122 122]
 [205 224  76  76]]
[[238 236  43  43]
 [236 236  47  47]
 [205 228  76  76]
 [214 228  69  69]
 [202 202 122 122]
 [209 224  76  76]]
[[213 232  63  63]
 [209 226  84  84]
 [214 228  69  69]
 [214 231  69  69]
 [202 202 122 122]]
[[213 232  63  63]
 [214 228  69  69]
 [211 231  69  69]
 [ 50 150  84  84]]
[[217 232  63  63]
 [217 231  69  69]]
[[209 228  76  76]]
[[217 235  63  63]]
[[ 46 147  92  92]
 [217 231  69  69]
 [ 92 155  84  84]]
[[217 235  63  63]]
[[242 238  43  4

KeyboardInterrupt: 